### ISSUE TITLE
how can add cityname and area ?

### ISSUE THREAD

**Issue by rab14191** [php-cuong/magento2-regions-manager#3]
i want to add city name and area it is possible ?

**Comment by php-cuong** [comment]
Yes, I can do it for you. The cost of this task about $250

**Comment by wartodolin** [comment]
hello @php-cuong , do you have any chat account so we can chat about customize city form 

Thanks

**Comment by php-cuong** [comment]
@wartodolin please contact me on the fanpage https://www.facebook.com/giaphugroupcom/

we will discuss your requirements

**Comment by php-cuong** [comment]
You can view this video, This is the Regions Manager Pro extension, it supports to display state, city, district, ward via drop-down.

See the video
https://www.youtube.com/watch?v=av4C1u5_BWY

With state drop-down, city drop-down, district drop-down, ward drop-down.
