### ISSUE TITLE
Mass Deletion of Regions

### ISSUE THREAD

**Issue by Aggreyluts** [php-cuong/magento2-regions-manager#4]
You cannot delete regions using the mass action delection option

**Comment by php-cuong** [comment]
Please describe the error with more details. What is the Magento version you using?

**Comment by l00k** [comment]
Uncaught Error: Call to undefined method PHPCuong\Region\Model\ResourceModel\Region\Grid\Collection::_getAllIdsSelect()

PHP: 7.0
Magento: 2.1.6
