### ISSUE TITLE
Magento ver. 2.2.0

### ISSUE THREAD

**Issue by Ralfefernandes** [php-cuong/magento2-regions-manager#5]
I just installed this extension using composer command

error code:  rwas@hp:/var/www/html/magento2$ sudo php bin/magento setup:di:compile
Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 50.0 Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 52.0 Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec Repositories code generation... 2/7 [========>-------------------]  28% 2 secs 1Service data attributes generation... 2/7 [========>-------------------]  28% 2 Service data attributes generation... 3/7 [============>---------------]  42% 2 Application code generator... 3/7 [============>---------------]  42% 2 secs 152Application code generator... 4/7 [================>-----------]  57% 5 secs 172Interceptors generation... 4/7 [================>-----------]  57% 5 secs 172.0 Interceptors generation... 5/7 [====================>-------]  71% 9 secs 188.0 Area configuration aggregation... 5/7 [====================>-------]  71% 9 secsArea configuration aggregation... 6/7 [========================>---]  85% 13 secInterception cache generation... 6/7 [========================>---]  85% 13 secs 250.0 MiBErrors during compilation:
	PHPCuong\Region\Model\ResourceModel\Region\Grid\Collection
		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \PHPCuong\Region\Model\ResourceModel\Region\Grid\connection; File: 
/var/www/html/magento2/vendor/php-cuong/magento2-regions-manager/Model/ResourceModel/Region/Grid/Collection.php

Total Errors Count: 1

                                           
  [Magento\Framework\Validator\Exception]  
  Error during compilation

**Comment by php-cuong** [comment]
The problem was fixed in the version 2.2.1
